add spring security
yurkova-anastasia/people_activity pull request #3
Opened 2023-05-18 09:47 UTC by yurkova-anastasia

2023-06-04 08:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.0/2023-04-26__2_create_users.xml
> +            <column name="username" type="varchar(256)">
you can't change it here, write new migration

2023-06-04 08:59 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-05-16__1_change_password_for_user1.xml
> +    <changeSet id="1" author="anastasia.yurkova2003@gmail.com">
if I understood write, it's only for test_data, transfer it into test data, you can add it into all users in test_data generator

2023-06-04 09:00 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRequestDto.java
> +public class AuthenticationRequestDto {
add
@Accessors(chain = true)

2023-06-04 09:13 UTC, kolyago-vladislav requested changes

2023-06-04 09:13 UTC, kolyago-vladislav commented on databases/ku-users/migrations/intermediate-changelog.xml
add table Authorities, link it to Roles (MtoM) and rewrite your logic

2023-06-04 09:13 UTC, kolyago-vladislav commented on databases/ku-users/migrations/intermediate-changelog.xml
Authorities - users:read, users::wirte

2023-06-04 09:13 UTC, kolyago-vladislav commented on databases/ku-users/migrations/intermediate-changelog.xml
используй на эндпоинтах не hasRole, а hasAuthorities

2023-06-04 09:13 UTC, kolyago-vladislav commented on databases/ku-users/migrations/intermediate-changelog.xml
мы договорились так, что ты будешь через спринг дату делать?

2023-06-06 07:58 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_change_password_for_user.xml
> +<?xml version="1.0" encoding="UTF-8"?>
перенеси эту миграции в скрипт генерации тестовых данных

2023-06-06 08:00 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +        <sql>
используй встроенные команды ликвибейза вместо нативного sql

2023-06-06 08:01 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +            <column name="role_id" type="int">
почему int?

2023-06-06 08:01 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +            <column name="authority_id" type="int">
почему int?

2023-06-06 08:02 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +<?xml version="1.0" encoding="UTF-8"?>
добавь индексы на все foreign keys по всей базе юзерс в отдельной миграции

2023-06-06 08:04 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__4_fill_authorities.xml
> +        INSERT INTO authorities(authority_name, inserted_date_at_utc) VALUES
у тебя разрешения должны привязываться к конкретным эндпоинтам, а не к ролям 
user::read, device::write и тд

2023-06-06 08:04 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__4_fill_authorities.xml
> +        INSERT INTO authorities(authority_name, inserted_date_at_utc) VALUES
нет ролбэка

2023-06-06 08:05 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__4_fill_authorities.xml
> +        INSERT INTO authorities(authority_name, inserted_date_at_utc) VALUES
дату использой Now() в utc

2023-06-06 08:05 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__5_fill_role_authority_links.xml
> +<?xml version="1.0" encoding="UTF-8"?>
почему это лежит не в тест дате?

2023-06-06 08:08 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtTokenFilter.java
> +package com.ku.gateway.security.jwt;
отформатируй правильно

2023-06-06 08:09 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtTokenProvider.java
> +@PropertySource(ignoreResourceNotFound = true, value = "classpath:application.yml")
тебе не нужна эта аннотация

2023-06-06 08:10 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtTokenProvider.java
> +                .setExpiration(new Date(System.currentTimeMillis() + expiration)) // 1 week
вынеси в проперти это System.currentTimeMillis() + expiration - эту переменную

2023-06-06 08:11 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtTokenProvider.java
> +
всё ли спользуется?

2023-06-06 08:12 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtUser.java
> +@AllArgsConstructor
используй дату и аксессорс

2023-06-06 08:12 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtUser.java
> +    private LocalDateTime updatedDateAtUtc;
это точно необходимо всё?

2023-06-06 08:12 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtUserFactory.java
> +//    private static List<GrantedAuthority> mapToGrantedAuthorities(List<AuthenticationRoleDto> userRoles) {
удали

2023-06-06 08:13 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtUserFactory.java
> +public final class JwtUserFactory {
что за говно класс?

2023-06-06 08:16 UTC, kolyago-vladislav commented on ku-gateway/src/main/resources/application.yml
> +      expiration: 3600000
используй 2d здесь, а в setter Duration

2023-06-06 08:17 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationAuthorityDto.java
> +public class AuthenticationAuthorityDto {
назови без Аунтификейшн

2023-06-06 08:17 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +    private LocalDateTime  updatedDateAtUtc;
зачем тебе это + id?

2023-06-06 08:18 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationUserDto.java
> +    private Set<AuthenticationRoleDto> roles;
зачем тебе весь юзер?

2023-06-19 09:49 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-04-28__1_fill_users.xml
> +            SET "password"='$2a$12$TwyA3BAycKOqoRohVWBgvOkTutmQzSMcMegm1mIU2zI/1NX0uJmqy'
зачем тебе новый changeSet? измени это 'password' || s.sery,

2023-06-19 09:50 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +        <sql>
не используй нативный sql, перепиши на добавление через команды ликвы

2023-06-19 09:51 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.0/2023-04-26__2_create_users.xml
> +            <column name="surname" type="varchar(16)">
почему здесь до сих пор изменения? - ты не можешь изменять миграции из v.1.0.0, ещё раз тебе это повторяю

2023-06-19 09:52 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__2_create_authorities.xml
> +    </changeSet>
добавь конкретные значения сюда через команды ликвы

2023-06-27 10:57 UTC, kolyago-vladislav requested changes

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +        <sql>
сделай это в основных миграциях, так как эти данные буду добавляться и на прод

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +        <sql>
с тестовыми они будут одинаковые

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +            <column name="role_id" type="bigserial">
bigserial испольуется только для PK используй BIGINT

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-06__4_create_index_for_foreign_key.xml
> +
пустая строка

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +    private LocalDateTime insertedDateAtUtc;
для чего тебе дата добавления?

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +public class AuthenticationRoleDto {
у тебя есть AuthenticationRequestDto, если я правильно понимаю, то более логично назвать AuthenticationResponseDto

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +public class AuthenticationRoleDto {
ладно, даже не так, мне не нравится

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +public class AuthenticationRoleDto {
чушь

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +public class AuthenticationRoleDto {
создай 2 дто:
AuthenticationRequestDto - у тебя уже есть
AuthenticationResponseDto - то, что надо получить в итоге
в котором должно вернуться:
Set(String) - roleNames
Set(String) - authorityNames

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +public class AuthenticationRoleDto {
всё ненужное удали

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/config/SecurityConfig.java
> +        prePostEnabled = true
съехал формат

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/config/SecurityConfig.java
> +        http.addFilterBefore(
уверен, что влезет в одну строку

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationRoleDto.java
> +public class AuthenticationRoleDto {
если я правильно понял, ты используешь только метод hasAutority, поэтому если можно ограничится списком authorityNames, то ограничься только им

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtTokenFilter.java
> +    protected void doFilterInternal(HttpServletRequest request,
отформатируй красив, сейчас говно

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/config/SecurityConfig.java
> +@RequiredArgsConstructor
мы договорились через setter автоварить по-моему

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/controller/AuthenticationController.java
> +                .authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
вынеси это в переменную, тогда не придётся так некрасиво форматировать код 
new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword())

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/controller/AuthenticationController.java
> +                .authenticate(new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword()));
используй var

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +            ('WRITE', NOW()),
чушь полная

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +            ('WRITE', NOW()),
user::read
device::read

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +            ('WRITE', NOW()),
сейчас у тебя чушь написана

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/JwtUserDetailsService.java
> +            }
пробрасывай на уровне сервисов в том модуле, где ты ищешь, своё исключение, а не вот это вот

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/JwtUserDetailsService.java
> +        }
используй SneakyThrows в таких случаях

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/JwtUserDetailsService.java
> +public class JwtUserDetailsService implements UserDetailsService {
UserDetailsServiceImpl

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/JwtUser.java
> +public class JwtUser implements UserDetails {
UserDetailsImpl

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-gateway/src/main/resources/application.yml
> +      issuer: anastacia
используй как в миграциях

2023-06-27 10:57 UTC, kolyago-vladislav commented on ku-users/src/main/java/com/ku/users/controller/UserController.java
> +    public AuthenticationUserDto findByUsername(
зачем тебе доп эндпоинт? добавь в findAll фильтр usernames и используй тот эндпоинт

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +            <column name="authority_name" value="WRITE"/>
я тебе уже писал, не будет у тебя таких широкий authority
добавь на данный момент user::read, user::write и тд

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.0/2023-04-26__4_create_user_role_links.xml
зачем ты редактируешь 1.0.0 миграцию?

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +            <column name="authority_name" value="WRITE"/>
зачем тебе это в тест дате? если ты в обычных миграциях их добавляешь

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__2_create_authorities.xml
> +    </changeSet>
смотри комменты в тест дате

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +            <column name="role_id" type="bigserial">
не исправлено

2023-06-27 10:57 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-06__4_create_index_for_foreign_key.xml
> +
не исправлено

2023-06-27 13:42 UTC, yurkova-anastasia commented on databases/ku-users/migrations/test-data/2023-06-04__4_fill_authorities.xml
> +            <column name="authority_name" value="WRITE"/>
+

2023-06-27 13:42 UTC, yurkova-anastasia commented on databases/ku-users/migrations/v.1.0.0/2023-04-26__2_create_users.xml
> +            <column name="surname" type="varchar(16)">
+

2023-06-27 13:42 UTC, yurkova-anastasia commented on databases/ku-users/migrations/v.1.0.0/2023-04-26__4_create_user_role_links.xml
+

2023-06-27 13:42 UTC, yurkova-anastasia commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__2_create_authorities.xml
> +    </changeSet>
+

2023-06-27 13:42 UTC, yurkova-anastasia commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +            <column name="role_id" type="bigserial">
+

2023-06-27 13:42 UTC, yurkova-anastasia commented on databases/ku-users/migrations/v.1.0.1/2023-06-06__4_create_index_for_foreign_key.xml
> +
+

2023-06-30 21:32 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__2_create_authorities.xml
> +            <column name="authority_name" type="varchar(256)">
добавь уникальный констрейнт в новом ченжсете

2023-06-30 21:33 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__2_create_authorities.xml
> +            <column name="inserted_date_at_utc" valueDate="NOW()"/>
привыкай везде, где пишешь now писать at utc

2023-06-30 21:34 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/2023-06-04__3_create_role_authority_links.xml
> +            <column name="active" type="boolean">
не увидел индекса на role_id authority_id where active = true

2023-06-30 21:34 UTC, kolyago-vladislav commented on databases/ku-users/migrations/v.1.0.1/cumulative-changelog.xml
> +    <include file="2023-06-027__5_change_type_of_user_role_id.xml" relativeToChangelogFile="true"/>
что такое 027?

2023-06-30 21:37 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationResponseDto.java
> +}
тебе это не надо

2023-06-30 21:37 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthorityDto.java
> +}
и это не надо

2023-06-30 21:38 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationUserDto.java
> +    private Set<AuthenticationResponseDto> roles;
вместо этого Set<String> autrhities (authorityNames) - собери этот сет на уровне сервиса

2023-06-30 21:39 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/UserDetailsServiceImpl.java
> +        UserDetailsImpl jwtUser = UserDetailsImpl.builder()
используй var везде

2023-06-30 21:40 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthorityDto.java
> +public class AuthorityDto {
удали

2023-06-30 21:40 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationResponseDto.java
> +public class AuthenticationResponseDto {
удали

2023-06-30 21:44 UTC, kolyago-vladislav commented on ku-users/src/main/java/com/ku/users/service/UserService.java
> +        var userDto = userMapper.toAuthenticationUserDto(user);
вот здесь тебе надо получить 2 сета 
1. сет<String> roles (имена ролей)
2. сет<String> authorities (имена authority)

2023-07-12 11:32 UTC, kolyago-vladislav commented on ku-common/src/main/java/com/ku/common/dto/AuthenticationUserDto.java
> +public class AuthenticationUserDto {
у тебя есть AuthenticationRequestDto, сделай по аналогии AuthenticationResponseDto

2023-07-12 11:35 UTC, kolyago-vladislav commented on ku-gateway/src/main/java/com/ku/gateway/security/jwt/UserDetailsImpl.java
> +    public Object getId() {
зачем ты Object возвращаешь?

2023-07-12 11:36 UTC, kolyago-vladislav commented on ku-users/src/main/java/com/ku/users/service/UserService.java
> +                                       .map(Authority::getAuthorityName)
сделай этот код сверху в переменную, слишком большая лесенка, некрасиво
user.getRoles().stream()
                                       .flatMap(role -> role.getAuthorities().stream())
                                       .map(Authority::getAuthorityName)
                                       .collect(Collectors.toSet()))

2023-07-18 12:18 UTC, kolyago-vladislav approved these changes

2023-07-19 11:03 UTC, merged